name: kanyoni
description: "A music player."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  get: ^4.6.6
  just_audio: ^0.9.42
  audio_video_progress_bar: ^2.0.3
  rxdart: ^0.28.0
  marquee: ^2.3.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  on_audio_query_forked:
  sliding_up_panel: ^2.0.0+1
  permission_handler: ^12.0.1
  azlistview: ^2.0.0
  shared_preferences: ^2.3.5
  path: ^1.9.0
  audio_service: ^0.18.16
  audio_session: ^0.1.24
  scrollable_positioned_list: ^0.2.3
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1

  # Local db
  hive: ^2.2.3
  path_provider: ^2.1.5
  flutter_audio_waveforms: ^1.2.1+8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application
  assets:
    - assets/icon/
    - assets/images/
